# Generated by Django 5.0.4 on 2024-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='data_images/')),
                ('name', models.CharField(max_length=128)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(related_name='images', to='img_app.tag')),
            ],
        ),
    ]
